name = "RootsByDistribution"
uuid = "9cc1a53d-9841-4c61-b4b4-384b150dc85a"
authors = ["Constantin Bilz <cbilz@posteo.net>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"
